[package]
name = "zertz-core"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3.2"
serde = { version = "1.0.152", features = ["derive"] }
serde-big-array = "0.4.1"
serde_json = "1.0.91"
thiserror = "1.0.38"
